services:
  postgres:
    container_name: postgres
    image: postgres:15-alpine
    env_file:
      - .env
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - server_net

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:8
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - server_net
  
  blazor:
    container_name: blazor
    depends_on:
      - postgres
    env_file:
      - .env
    build:
      context: ./Fide
    networks:
      - server_net
  
  nginx:
    container_name: nginx
    build: ./Nginx
    restart: on-failure
    ports:
      - 80:80
    depends_on:
      - blazor
      - pgadmin
    env_file:
      - .env
    networks:
      - server_net

volumes:
  db_vol: {}

networks:
  server_net:
    driver: bridge