name: Fide Jobs

on:
  push:
    branches: [ master ]
    paths:
    - Fide/**
  pull_request:
    branches: [ master ]
    paths:
    - Fide/**

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    
    - name: Restore dependencies
      working-directory: ./Fide
      run: dotnet restore
    
    - name: Build
      working-directory: ./Fide
      run: dotnet build --configuration Release --no-restore
    
    - name: Run tests
      working-directory: ./Fide
      run: dotnet test --configuration Release --no-build --verbosity normal