name: Pyflakes Code Check

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Pyflakes
        run: pip install pyflakes

      - name: Run Pyflakes
        run: pyflakes Aomaca/
